name: deploy React application with Ngnix

on:
  push:
    branches:
      - main
job: 
  build:
    runs-on: ubuntu-latest

    steps:
    -   name: checkout code 
        uses: actions/checkout@v3

    -   name: login to AWS ECR 
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 471112561825.dkr.ecr.ap-south-1.amazonaws.com
    
    -   name: build image
        run: |
          docker build -t dev/srn:latest .
          docker tag dev/srn:latest 471112561825.dkr.ecr.ap-south-1.amazonaws.com/dev/srn:latest
          docker push 471112561825.dkr.ecr.ap-south-1.amazonaws.com/dev/srn:latest
